scaling = 16
forward_speed = 4
side_speed = 7
tile_size = 4
raft_size = 2
restart_timer = 5
dash_distance = 5
dash_cooldown = 1
attack_time = 1
push_distance = 5
push_distance_rem_k = 0.5
seagull_height = 10
seagull_speed = 8
seagull_rotate_speed = 90
limit = 15
gravity = 10
poop_cooldown = 5
collide_speed = 2
slide_speed = 8
music_volume = 0.3

[shark]
count = 3
depth = -3
speed = 5
extra_move_radius = 10
attack_prob = 0.5

[water]
color = "#608ab899"
z = -0.2

[camera]
distance = 20
rot = 30
attack = 60
fov = 60
speed = 2

[crab_animation]
legs_freq = 20
legs_amp = 20
z = 0.5

[wave]
dir = [1, 3]
freq = 1
vertical_amp = 0.1
angle_amp = 5
speed = 1
